# Generated by Django 2.1.2 on 2018-10-12 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text',
        ),
    ]
