# Generated by Django 2.1.2 on 2018-10-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_delete_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
