# Generated by Django 2.1.2 on 2018-10-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rating_de',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='rating_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='rating_ru',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='section_de',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='section_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='section_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
