# Generated by Django 2.1.2 on 2018-10-12 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20181013_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='rating_de',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='rating_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='rating_ru',
        ),
    ]
